[package]
name = "proxy-wasm-http-cookie-header-convert"
version = "0.3.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
proxy-wasm = "0.2.2"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
